lucianozapata/DD2480VT221

.github/workflows/gradle.yml
Implemented Github actions with gradle. Should make it so that the unit testing is automated and runs with every push and pull request to the main branch. 
Fixes #17
=> Implementing Github Actions for the restructured skeleton #17.

README.md
First draft of the README, this will be updated continuously as new features are added.
=> First draft of the README resolve #18

src/main/java/com/group24/decide/LIC.java, src/main/java/com/group24/decide/Utility.java, src/test/java/com/group24/decide/LICTest.java
Add LIC condition4 and corresponding test.
=> Fix: issue#5

src/test/java/com/group24/decide/UtilityTest.java
Add unit-test for chooseQuadrant() function in Utility class.
=> Fixed: issue#47

src/main/java/com/group24/decide/LIC.java, src/main/java/com/group24/decide/Utility.java, src/test/java/com/group24/decide/LICTest.java
=> LIC5 to issue #6

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
Implement LIC condition7 and its unit-test.
=> Fixed: issue#8

src/main/java/com/group24/decide/LIC.java, src/main/java/com/group24/decide/Utility.java, src/test/java/com/group24/decide/LICTest.java, src/test/java/com/group24/decide/UtilityTest.java
Implement LIC condition8 and its unit-test. Implement a new utility method findSmallestCircle used by condition8. Also implement the unit-test for method findSmallestCircle.
=> Fixed: issue#9

build.gradle
Creates a detailed test report
Open the following file in your browser build/jacocoHtml/index.html
=> Added jacoco plugin for test coverage (resolves #60)

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
Adds some more tests for LIC0 and checks that the criterias for the functions if furfilled. Linked with #57
=> feat: Issue#57

build.gradle
Added gradle run configuration, allows to run the code as stand-alone program with the wrapper
```bash
./gradlew run 
gradlew.bat run
```
=> Feat: Added gradle run configuration #62

src/main/java/com/group24/decide/Decide.java, src/test/java/com/group24/decide/DecideTest.java
Implement a method to calculate PUM and its unit test.
=> Feat: PUM issue#53

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
=> Feat: Implemented LIC condition 12 and its unit-test. #13

.github/workflows/javadoc.yml, README.md, src/main/java/com/group24/decide/LIC.java
- Updated README
- Added github action to automatically create Javadocs and publish them to github-pages.
=> Updated Readmeand Javadoc (resolve issue#52)

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
=> feat: Implemented LIC1 and tests #2

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
Implemented LIC condition 11 along its unit-tests.
Fixes #12
=> Feat: Added LIC condition 11 #12

src/main/java/com/group24/decide/LIC.java, src/main/java/com/group24/decide/Utility.java, src/test/java/com/group24/decide/LICTest.java, src/test/java/com/group24/decide/UtilityTest.java
Implementation of **LIC2** and tests for it. 
Conditions for LIC2 corresponds to #3
=> feat: LIC2 implementation with 4 tests

src/main/java/com/group24/decide/LIC.java, src/main/java/com/group24/decide/Utility.java, src/test/java/com/group24/decide/LICTest.java
Feat: LIC condition 9 including test
=> Feat: LIC condition 9 including test, #issue79

src/main/java/com/group24/decide/Decide.java, src/test/java/com/group24/decide/DecideTest.java
Implemented the Final Unlocking Vector (FUV) and JUnit-tests for it. Solves issue #54
=> feat: Implemented Final unlocking vector and tests

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
=> Feat: LIC condition 10 including test, #issue11

README.md
Implemented documentation for our Ways of working where we reflect on all different stages and how we can reach the next. 
#78
=> Feat: Implemented ways of working documentation

src/main/java/com/group24/decide/Decide.java, src/main/java/com/group24/decide/Launcher.java, src/test/java/com/group24/decide/DecideTest.java
Added a constructor to Decide class. 
Changed the variables in the class. 
Added two methods calcCMV() and launch(). 
Added the Launcher class to replace Decide to serve as the main class. 
Refactored DecideTest class to be compatible with the Decide class.
=> Refact: refactor Decide class (issue#76)

src/main/java/com/group24/decide/Datapoints.java, src/main/java/com/group24/decide/Decide.java, src/main/java/com/group24/decide/LIC.java, src/main/java/com/group24/decide/Parameter.java, src/main/java/com/group24/decide/Utility.java
Merged the current main branch to prevent conflics
=> Improved Javadocs resolves issue#77

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
Fixed the bug in method Condition12() and changed the corresponding test.
=> Fixed: bug in Condition12 (issue#85)

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/DecideTest.java, src/test/java/com/group24/decide/LICTest.java, src/test/java/com/group24/decide/UtilityTest.java
Delete some unnecessary codes.
=> Fixed: clean up the code (issue89)

src/test/java/com/group24/decide/LICTest.java
Rechecked all tests and created new ones for LIC. #86
=> feat: Implemented more input-validation tests for LIC

src/main/java/com/group24/decide/Utility.java, src/test/java/com/group24/decide/DecideTest.java, src/test/java/com/group24/decide/LICTest.java, src/test/java/com/group24/decide/UtilityTest.java
Created a more clear documentation of tests. Linked with #92
=> Refactor: Added clearer documentation of tests. #92

build.gradle
Change main class so gradle wrapper can run the code as described in the README
=> Fix: updated main class in gradle.build config (#98)

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/LICTest.java
=> Fix: LIC 5,9,10 #issue100

src/main/java/com/group24/decide/LIC.java, src/test/java/com/group24/decide/DecideTest.java, src/test/java/com/group24/decide/LICTest.java
Fixed condition8 and tests relevant to condition8. #102
=> Fix: LIC condition8 (issue#102)
